#! /bin/bash

#
#    Tangaza
#
#    Copyright (C) 2010 Nokia Corporation.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#    Author: Billy Odero
#

set -e
TGZ_LOCATION=/usr/lib/tangaza/

#stop tangaza
#echo "Stopping tangaza"
#/etc/init.d/tangaza stop

#remove tangaza from startup scripts
#echo "Removing tangaza from startup scripts"
#update-rc.d -f tangaza remove

echo "Restoring backed-up conf files"
#1. Asterisk
mv /etc/asterisk/extensions.conf.tgzbak /etc/asterisk/extensions.conf

#2. kannel
mv /etc/kannel/kannel.conf.tgzbak /etc/kannel/kannel.conf
mv /etc/kannel/modem.conf.tgzbak /etc/kannel/modem.conf

#3. apache
rm /etc/apache2/sites-enabled/tangaza-sms
mv /etc/tangaza/tangaza-sms.tgzbak /etc/tangaza/tangaza-sms

#if [ -f '/etc/apache2/ports.conf.bak' ]; then
#    mv /etc/apache2/ports.conf.bak /etc/apache2/ports.conf
#fi

#4. Django link files
TGZ_DJANGO_MEDIA=/usr/share/tangaza/media
find $TGZ_DJANGO_MEDIA -type l -exec rm {} +;

#5. Nagios symlinks
rm /usr/lib/nagios/plugins/tangaza-monitor

sed -i 's/cfg_dir=/etc/tangaza/nagios//g' /etc/nagios3/nagios.cfg

#DEBHELPER#

exit 0
